---
- name: Setup Development Tools
  hosts: all
  become: yes

  vars:
    ghostty_version: "1.1.3"
    tmux_version: "3.5a"
    fd_version: "10.2.0"
    zoxide_version: "0.9.7"
    fzf_version: "0.48.0"
    neovim_version: "0.11.0"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - build-essential
          - curl
          - git
          - unzip
          - pkg-config
          - libncurses-dev
          - libevent-dev
          - libssl-dev
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Ghostty
      shell: |
        curl -LO https://github.com/ghostty-org/ghostty/releases/download/v{{ ghostty_version }}/ghostty-{{ ghostty_version }}-linux-x86_64.tar.gz
        tar -xzf ghostty-{{ ghostty_version }}-linux-x86_64.tar.gz
        mv ghostty /usr/local/bin/
      args:
        creates: /usr/local/bin/ghostty

    - name: Install tmux
      shell: |
        curl -LO https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
        tar -xzf tmux-{{ tmux_version }}.tar.gz
        cd tmux-{{ tmux_version }}
        ./configure && make && make install
      args:
        creates: /usr/local/bin/tmux

    - name: Install fd
      shell: |
        curl -LO https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-v{{ fd_version }}-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf fd-v{{ fd_version }}-x86_64-unknown-linux-gnu.tar.gz
        mv fd-v{{ fd_version }}-x86_64-unknown-linux-gnu/fd /usr/local/bin/
      args:
        creates: /usr/local/bin/fd

    - name: Install zoxide
      shell: |
        curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
      args:
        creates: /usr/local/bin/zoxide

    - name: Install fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        version: "{{ fzf_version }}"
      register: fzf_clone

    - name: Run fzf install script
      shell: ~/.fzf/install --all
      when: fzf_clone.changed

    - name: Install Neovim
      shell: |
        curl -LO https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux64.tar.gz
        tar -xzf nvim-linux64.tar.gz
        mv nvim-linux64/bin/nvim /usr/local/bin/
      args:
        creates: /usr/local/bin/nvim

